spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: true # 스프링 배치 자동 실행이 안되도록 설정.
  application:
    name: spring-batch-kotlin
  datasource:
    url: jdbc:mysql://localhost:3311/kitchen
    username: kitchenuser
    password: kitchen
    driver-class-name: com.mysql.cj.jdbc.Driver
