spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: true # 스프링 배치 자동 실행이 안되도록 설정.
  application:
    name: spring-batch-kotlin
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring_batch_prac
#    username: spring
#    password: batch
#    driver-class-name: com.mysql.cj.jdbc.Driver
